apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: clipper-frontend
spec:
  template:
    spec:
      containers:
        - image: FRONTEND_IMAGE
          ports:
            - containerPort: 8080
