import os
import sys
import json
import logging
import signal
import time
import threading
from http.server import HTTPServer, BaseHTTPRequestHandler
from concurrent.futures import ThreadPoolExecutor

# Import from shared modules
from shared.core.pipeline import Pipeline
from supabase import create_client

# Setup logging
logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO"),
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("worker_gpu")

# Initialize Supabase
supabase = create_client(
    os.environ["SUPABASE_URL"],
    os.environ["SUPABASE_KEY"]
)


# ── Health Check HTTP Server ──────────────────────────────────────────
class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(b'{"status":"ok","worker":"gpu"}')

    def log_message(self, format, *args):
        pass  # suppress access logs


def start_health_server():
    port = int(os.getenv("PORT", "8080"))
    server = HTTPServer(("0.0.0.0", port), HealthHandler)
    logger.info(f"Health server listening on port {port}")
    server.serve_forever()


# ── Processing Logic ──────────────────────────────────────────────────
def process_job(job_data: dict) -> None:
    """
    Execute the core clipping pipeline for a job.
    """
    job_id = job_data.get("job_id")
    config = job_data.get("config", {})
    
    if not job_id:
        logger.error("Job data missing job_id")
        return

    logger.info(f"[{job_id}] Received job. Starting processing...")
    
    # Workspace directory inside container
    workspace_root = os.getenv("CLIPPER_WORKSPACE", "/app/workspace")
    job_dir = os.path.join(workspace_root, job_id)
    os.makedirs(job_dir, exist_ok=True)

    # 1. Update Status to Processing
    try:
        supabase.table("job").update({"status": "processing"}).eq("id", job_id).execute()
        
        # 2. Progress Callback
        def progress_callback(step, message, progress):
            logger.info(f"[{job_id}] {step}: {message} ({progress}%)")

        # 3. Run Pipeline Initial Steps (Download -> Transcribe -> Analyze)
        pipeline = Pipeline(job_dir, config, progress_callback)
        clips_metadata = pipeline.run()

        if not clips_metadata:
            logger.warning(f"[{job_id}] No clips generated by analyzer.")
            supabase.table("job").update({"status": "completed", "clips": "[]"}).eq("id", job_id).execute()
            return

        # 4. Process each clip (Clip + Reframe)
        processed_clips = []
        for i, clip in enumerate(clips_metadata):
            try:
                logger.info(f"[{job_id}] Processing Clip {i+1}/{len(clips_metadata)}")
                
                # Temporarily disable captions in config for this stage
                gpu_config = config.copy()
                gpu_config['enable_captions'] = False
                gpu_config['enable_hook'] = False # GPU worker only does the base video
                
                pipeline.config = gpu_config
                final_meta = pipeline.export_single_clip(clip, clip_index=i)
                processed_clips.append(final_meta)
                
            except Exception as clip_err:
                logger.error(f"[{job_id}] Failed to process clip {i}: {clip_err}")

        # 5. Update Database with results
        supabase.table("job").update({
            "status": "completed",
            "clips": json.dumps(processed_clips)
        }).eq("id", job_id).execute()
        
        # 6. Push to Caption Topic for worker_node (The Real Heavy Rendering)
        if config.get("enable_captions", True):
            push_to_caption_queue(job_id, job_dir, processed_clips, config)
        
        logger.info(f"[{job_id}] Worker GPU finished successfully.")

    except Exception as e:
        logger.error(f"[{job_id}] Pipeline failed: {e}", exc_info=True)
        supabase.table("job").update({
            "status": "error",
            "error": str(e)
        }).eq("id", job_id).execute()


def push_to_caption_queue(job_id, job_dir, clips, config):
    """
    Publish a message to the captioning topic for worker_node.
    """
    project_id = os.getenv("GCP_PROJECT_ID")
    topic_id = os.getenv("PUBSUB_TOPIC_CAPTION") or "clipper-caption-jobs"

    if not project_id:
        logger.warning(f"[{job_id}] GCP_PROJECT_ID not set, skipping caption queue push")
        return

    try:
        from google.cloud import pubsub_v1
        publisher = pubsub_v1.PublisherClient()
        topic_path = publisher.topic_path(project_id, topic_id)
        
        message_data = json.dumps({
            "job_id": job_id,
            "job_dir": job_dir,
            "clips": clips,
            "config": config,
            "timestamp": time.time()
        }).encode("utf-8")
        
        publisher.publish(topic_path, message_data).result(timeout=30)
        logger.info(f"[{job_id}] Pushed {len(clips)} clips to captioning topic: {topic_id}")
    except Exception as e:
        logger.error(f"[{job_id}] Failed to push to caption queue: {e}")


# ── Pub/Sub Listener ──────────────────────────────────────────────────
def pull_messages():
    project_id = os.getenv("GCP_PROJECT_ID")
    subscription_id = os.getenv("PUBSUB_SUBSCRIPTION_JOBS") or "clipper-jobs-sub"

    if not project_id:
        logger.warning("GCP_PROJECT_ID not set — running in demo mode")
        while True:
            time.sleep(30)

    from google.cloud import pubsub_v1
    retry_delay = 10

    while True:
        try:
            subscriber = pubsub_v1.SubscriberClient()
            subscription_path = subscriber.subscription_path(project_id, subscription_id)
            logger.info(f"Connecting to Pub/Sub: {subscription_path}")

            def callback(message):
                try:
                    data = json.loads(message.data.decode("utf-8"))
                    logger.info(f"Received job: {data.get('job_id')}")
                    process_job(data)
                    message.ack()
                except Exception as e:
                    logger.error(f"Error processing message: {e}", exc_info=True)
                    message.nack()

            streaming_pull_future = subscriber.subscribe(subscription_path, callback=callback)

            logger.info(f"Listening for messages on {subscription_id}...")
            with subscriber:
                try:
                    streaming_pull_future.result()
                except Exception as e:
                    if "NotFound" in str(e) or "404" in str(e):
                        logger.error(f"CRITICAL: Subscription '{subscription_id}' not found in project '{project_id}'. "
                                     "Please ensure it exists in GCP Console or check your GCP_PROJECT_ID env.")
                    streaming_pull_future.cancel()
                    raise e
        except Exception as e:
            logger.error(f"Pub/Sub Listener Error: {e}")
            time.sleep(retry_delay)
            retry_delay = min(retry_delay * 2, 300)


def handle_shutdown(signum, frame):
    logger.info("Shutdown signal received, exiting gracefully...")
    sys.exit(0)


if __name__ == "__main__":
    signal.signal(signal.SIGTERM, handle_shutdown)
    signal.signal(signal.SIGINT, handle_shutdown)

    health_thread = threading.Thread(target=start_health_server, daemon=True)
    health_thread.start()

    pull_messages()
