import os
import sys
import json
import logging
import signal
import time
import threading
from http.server import HTTPServer, BaseHTTPRequestHandler

# Import from shared modules
from shared.core.pipeline import Pipeline
from supabase import create_client

# Setup logging
logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO"),
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("worker_gpu")

# Initialize Supabase
supabase = create_client(
    os.environ["SUPABASE_URL"],
    os.environ["SUPABASE_KEY"]
)

# Global event untuk Graceful Shutdown
shutdown_event = threading.Event()

# ── Database Retry Wrapper ─────────────────────────────────────────────
def update_job_db(job_id: str, data: dict, max_retries: int = 3):
    """
    Fungsi wrapper untuk update Supabase dengan mekanisme Retry (Exponential Backoff).
    Menghindari error 'Broken pipe' saat Cloud Run mengalami network blip.
    """
    for attempt in range(max_retries):
        try:
            return supabase.table("job").update(data).eq("id", job_id).execute()
        except Exception as e:
            if attempt == max_retries - 1:
                logger.error(f"[{job_id}] Final attempt to update Supabase failed: {e}")
                raise
            sleep_time = 2 ** attempt
            logger.warning(f"[{job_id}] Supabase update failed: {e}. Retrying in {sleep_time}s...")
            time.sleep(sleep_time)


# ── Health Check HTTP Server ──────────────────────────────────────────
class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        status = "ok" if not shutdown_event.is_set() else "shutting_down"
        self.wfile.write(json.dumps({"status": status, "worker": "gpu"}).encode())

    def log_message(self, format, *args):
        pass  # suppress access logs

def start_health_server():
    port = int(os.getenv("PORT", "8080"))
    server = HTTPServer(("0.0.0.0", port), HealthHandler)
    logger.info(f"Health server listening on port {port}")
    
    # Run server until shutdown is triggered
    while not shutdown_event.is_set():
        server.handle_request()


# ── Processing Logic ──────────────────────────────────────────────────
def process_job(job_data: dict) -> None:
    job_id = job_data.get("job_id")
    config = job_data.get("config", {})
    
    if not job_id:
        logger.error("Job data missing job_id")
        return

    logger.info(f"[{job_id}] Received job. Starting processing...")
    workspace_root = os.getenv("CLIPPER_WORKSPACE", "/app/workspace")
    job_dir = os.path.join(workspace_root, job_id)
    os.makedirs(job_dir, exist_ok=True)

    try:
        # 1. Update Status to Processing (Menggunakan Retry)
        update_job_db(job_id, {"status": "processing"})
        
        def progress_callback(step, message, progress):
            logger.info(f"[{job_id}] {step}: {message} ({progress}%)")

        # 3. Run Pipeline Initial Steps
        pipeline = Pipeline(job_dir, config, progress_callback)
        clips_metadata = pipeline.run()

        if not clips_metadata:
            logger.warning(f"[{job_id}] No clips generated by analyzer.")
            update_job_db(job_id, {"status": "completed", "clips": "[]"})
            return

        # 4. Process each clip
        processed_clips = []
        for i, clip in enumerate(clips_metadata):
            try:
                logger.info(f"[{job_id}] Processing Clip {i+1}/{len(clips_metadata)}")
                gpu_config = config.copy()
                gpu_config['enable_captions'] = False
                gpu_config['enable_hook'] = False
                
                pipeline.config = gpu_config
                final_meta = pipeline.export_single_clip(clip, clip_index=i)
                processed_clips.append(final_meta)
                
            except Exception as clip_err:
                logger.error(f"[{job_id}] Failed to process clip {i}: {clip_err}")

        # 5. Update Database with results (Menggunakan Retry)
        update_job_db(job_id, {
            "status": "completed",
            "clips": json.dumps(processed_clips)
        })
        
        # 6. Push to Caption Topic
        if config.get("enable_captions", True):
            push_to_caption_queue(job_id, job_dir, processed_clips, config)
        
        logger.info(f"[{job_id}] Worker GPU finished successfully.")

    except Exception as e:
        logger.error(f"[{job_id}] Pipeline failed: {e}", exc_info=True)
        try:
            update_job_db(job_id, {"status": "error", "error": str(e)})
        except Exception as db_err:
            logger.error(f"[{job_id}] Gagal menyimpan status error ke DB: {db_err}")


def push_to_caption_queue(job_id, job_dir, clips, config):
    project_id = os.getenv("GCP_PROJECT_ID")
    topic_id = os.getenv("PUBSUB_TOPIC_CAPTION") or "clipper-caption-jobs"

    if not project_id:
        logger.warning(f"[{job_id}] GCP_PROJECT_ID not set, skipping caption queue push")
        return

    try:
        from google.cloud import pubsub_v1
        publisher = pubsub_v1.PublisherClient()
        topic_path = publisher.topic_path(project_id, topic_id)
        
        message_data = json.dumps({
            "job_id": job_id, "job_dir": job_dir,
            "clips": clips, "config": config,
            "timestamp": time.time()
        }).encode("utf-8")
        
        publisher.publish(topic_path, message_data).result(timeout=30)
        logger.info(f"[{job_id}] Pushed {len(clips)} clips to captioning topic: {topic_id}")
    except Exception as e:
        logger.error(f"[{job_id}] Failed to push to caption queue: {e}")


# ── Pub/Sub Listener ──────────────────────────────────────────────────
def pull_messages():
    project_id = os.getenv("GCP_PROJECT_ID")
    subscription_id = os.getenv("PUBSUB_SUBSCRIPTION_JOBS") or "clipper-jobs-sub"

    if not project_id:
        logger.warning("GCP_PROJECT_ID not set — running in demo mode")
        while not shutdown_event.is_set():
            time.sleep(10)
        return

    from google.cloud import pubsub_v1
    retry_delay = 10

    while not shutdown_event.is_set():
        try:
            subscriber = pubsub_v1.SubscriberClient()
            subscription_path = subscriber.subscription_path(project_id, subscription_id)
            logger.info(f"Connecting to Pub/Sub: {subscription_path}")

            def callback(message):
                try:
                    data = json.loads(message.data.decode("utf-8"))
                    logger.info(f"Received job: {data.get('job_id')}")
                    process_job(data)
                    message.ack()
                except Exception as e:
                    logger.error(f"Error processing message: {e}", exc_info=True)
                    message.nack()

            streaming_pull_future = subscriber.subscribe(subscription_path, callback=callback)
            logger.info(f"Listening for messages on {subscription_id}...")
            
            with subscriber:
                # Loop until future is done OR shutdown is triggered
                while not shutdown_event.is_set() and not streaming_pull_future.done():
                    time.sleep(1)
                
                # Jika shutdown dipicu, batalkan langganan secara Graceful
                if shutdown_event.is_set():
                    logger.info("Cancelling Pub/Sub subscription due to shutdown...")
                    streaming_pull_future.cancel()
                    streaming_pull_future.result() # Wait to finish canceling without closing RPC channel abruptly

        except Exception as e:
            if not shutdown_event.is_set():
                logger.error(f"Pub/Sub Listener Error: {e}")
                time.sleep(retry_delay)
                retry_delay = min(retry_delay * 2, 300)


def handle_shutdown(signum, frame):
    logger.info("Shutdown signal received! Initiating graceful shutdown...")
    shutdown_event.set()


if __name__ == "__main__":
    # Register Graceful Shutdown signals
    signal.signal(signal.SIGTERM, handle_shutdown)
    signal.signal(signal.SIGINT, handle_shutdown)

    health_thread = threading.Thread(target=start_health_server, daemon=True)
    health_thread.start()

    pull_messages()
    logger.info("Worker process exited cleanly.")